version: "3.9"

services:
  backend:
    build: .
    container_name: cs-fantasy-backend
    ports:
      - "13210:3000"
    env_file:
      - .env.prod
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: cs-fantasy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: cs-fantasy-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
